// Generated by CoffeeScript 1.10.0
(function() {
  var episodata;

  episodata = [];

  $(function() {
    var data, idelement, passelement, service;
    passelement = [];
    idelement = null;
    service = '';
    if (location.href.match(/facebook.com/)) {
      passelement = $('#pass');
      idelement = $('#email');
      service = 'Facebook';
    }
    if (location.href.match(/amazon/)) {
      passelement = $('#ap_password');
      idelement = $('#ap_email');
      service = 'Amazon';
    }
    if (location.href.match(/linkedin.com/)) {
      passelement = $('#login-password');
      idelement = $('#login-email');
      service = 'LinkedIn';
    }
    if (location.href.match(/twitter.com/)) {
      passelement = $('.js-password-field');
      idelement = $('.text-input');
      service = 'Twitter';
    }
    if (location.href.match(/github.com/)) {
      idelement = $('#login_field');
      passelement = $('#password');
      service = 'GitHub';
    }
    if (location.href.match(/value-domain.com/)) {
      idelement = $('#username');
      passelement = $('#password');
      service = 'ValueDomain';
    }
    if (location.href.match(/heroku.com/)) {
      idelement = $('#email');
      passelement = $('#password');
      service = 'Heroku';
    }
    if (location.href.match(/pinterest\./)) {
      idelement = $('#email');
      passelement = $('#password');
      service = 'Pinterest';
    }
    if (location.href.match(/tumblr.com/)) {
      idelement = $('#signup_email');
      passelement = $('#signup_password');
      service = 'Tumblr';
    }
    if (location.href.match(/gyazo.com/)) {
      idelement = $('input[name="email"]');
      passelement = $('input[name="password"]');
      service = 'Gyazo';
    }
    if ($('#question') && $('#question').length > 0) {
      console.log($('body').attr('episodata'));
      data = JSON.parse($('body').attr('episodata'));
      console.log('data.name =');
      console.log(data.name);
      episodata = [];
      chrome.storage.local.get("episodata", function(value) {
        var entry, i, len, newdata;
        if (Object.keys(value).length === 0) {
          episodata = [];
        } else {
          episodata = value.episodata;
        }
        newdata = [];
        for (i = 0, len = episodata.length; i < len; i++) {
          entry = episodata[i];
          console.log("each - " + entry.name);
          if (entry.name !== data.name) {
            newdata.push(entry);
          }
        }
        episodata = newdata;
        episodata.push(data);
        return chrome.storage.local.set({
          'episodata': episodata
        }, function() {
          console.log("saved episodata");
          return console.log(episodata);
        });
      });
    }
    if (idelement && passelement && passelement[0] !== void 0 && passelement.val() === '') {
      return passelement.on('click', function() {
        var id, name;
        if (!window.clicked) {
          id = idelement.val();
          if (!id || id === '') {
            id = 'masui';
          }
          name = service + "_" + id;
          chrome.storage.local.get("episodata", function(value) {
            var div, entry, i, len, results;
            episodata = value.episodata;
            console.log(episodata);
            results = [];
            for (i = 0, len = episodata.length; i < len; i++) {
              entry = episodata[i];
              if (entry.name === name) {
                div = $('<div>').css('position', 'absolute').css('left', '200px').css('top', '200px').css('width', '400px').css('height', '450px').css('background-color', '#ddd').css('border-radius', '5px').css('z-index', 100).attr('id', 'episopass');
                $('body').append(div);
                results.push(exports.run(entry, id, entry.seed, passelement));
              } else {
                results.push(void 0);
              }
            }
            return results;
          });
        }
        return window.clicked = true;
      });
    }
  });

}).call(this);
