// Generated by CoffeeScript 1.12.4
(function() {
  $(function() {
    var idelement, passelement, service;
    passelement = [];
    idelement = null;
    service = '';
    if (location.href.match(/facebook.com/)) {
      passelement = $('#pass');
      idelement = $('#email');
      service = 'Facebook';
    }
    if (location.href.match(/amazon/)) {
      passelement = $('#ap_password');
      idelement = $('#ap_email');
      service = 'Amazon';
    }
    if (location.href.match(/linkedin.com/)) {
      passelement = $('#login-password');
      idelement = $('#login-email');
      service = 'LinkedIn';
    }
    if (location.href.match(/twitter.com/)) {
      passelement = $('.js-password-field');
      idelement = $('.text-input');
      service = 'Twitter';
    }
    if (location.href.match(/github.com/)) {
      idelement = $('#login_field');
      passelement = $('#password');
      service = 'GitHub';
    }
    if (location.href.match(/value-domain.com/)) {
      idelement = $('#username');
      passelement = $('#password');
      service = 'ValueDomain';
    }
    if (location.href.match(/heroku.com/)) {
      idelement = $('#email');
      passelement = $('#password');
      service = 'Heroku';
    }
    if (location.href.match(/pinterest\./)) {
      idelement = $('#email');
      passelement = $('#password');
      service = 'Pinterest';
    }
    if (location.href.match(/tumblr.com/)) {
      idelement = $('#signup_email');
      passelement = $('#signup_password');
      service = 'Tumblr';
    }
    if (location.href.match(/gyazo.com/)) {
      idelement = $('input[name="email"]');
      passelement = $('input[name="password"]');
      service = 'Gyazo';
    }
    if (idelement && passelement && passelement[0] !== void 0 && passelement.val() === '') {
      return passelement.on('click', function() {
        var browser, div, id, name, xhr;
        if (!window.clicked) {
          id = idelement.val();
          if (!id || id === '') {
            id = 'masui';
          }
          name = service + "_" + id;
          div = $('<div>').css('position', 'absolute').css('left', '200px').css('top', '200px').css('width', '400px').css('height', '300px').css('background-color', '#ddd').css('border-radius', '5px').css('z-index', 100).attr('id', 'episopass');
          $('body').append(div);
          browser = window.navigator.userAgent.toLowerCase();
          if (browser.indexOf("firefox" > -1)) {
            $.getJSON("http://episopass.com/" + name + ".json", function(data) {
              return exports.run(data, id, data.seed, passelement);
            });
          }
          if (browser.indexOf("chrome" > -1)) {
            xhr = new XMLHttpRequest();
            xhr.open("GET", "https://episopass.com/" + name + ".json", true);
            xhr.onreadystatechange = function() {
              var data;
              if (xhr.readyState === 4) {
                data = JSON.parse(xhr.responseText);
                return exports.run(data, id, data.seed, passelement);
              }
            };
            xhr.send();
          }
        }
        return window.clicked = true;
      });
    }
  });

}).call(this);
